directories:
  output: ./release
  buildResources: build
appId: com.yourcompany.materialmanager
productName: 素材管理器
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: build/icon.ico
mac:
  target:
    - dmg
  icon: build/icon.icns
linux:
  target:
    - AppImage
  icon: build/icon.png
electronDownload:
  mirror: https://npmmirror.com/mirrors/electron/
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  perMachine: true
  unicode: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
files: []
electronVersion: 28.1.0
